### ISSUE TITLE
Logo Design For Yoke

### ISSUE THREAD

**Issue by zularizal** [TarVK/Yoke#1]
Hi @TarVK , I'm a graphic designer. I have reviewed your project and I like it.

But you don't have a logo yet, so I'm interested in contributing by creating a free logo for your project.

What do you think?

**Comment by TarVK** [comment]
Hey Zularizal!

Thanks for your offer, however,  one of our group members has already designed a logo.
Even more, an animation version has already been created to be shown on the splash screen.
So there won't be a need for a logo for Yoke.

However, if you are eager to create a logo for something, I actually have some other projects for which I have been wanting (new) logos.
So if you are interested in helping with those, let me know!

**Comment by zularizal** [comment]
Yes I am interested..
Can you send the link project?

**Comment by TarVK** [comment]
Okay, one of the things that could use a logo is an application framework designed for modular open source development using web languages (through electron). 
And the other is an application that will be built using this framework, a quick access utility program.
Both are still in their infancy due to several redesigns of the architecture that have taken place.

The readme of the framework is lacking still, but here are links to both:
https://github.com/LaunchMenu/Bollib
https://github.com/LaunchMenu/LaunchMenu

**Comment by zularizal** [comment]
Hi @TarVK  sorry it's too late, this is my logo design for your project launch menu. This logo is inspired by a mac shortcut and speed icon.

What do you think? And what color do you like?
If there is something you want to change, let me know.

![bitmap](https://user-images.githubusercontent.com/38547278/55210168-b58b2a80-5218-11e9-9082-87b12ab15a5b.png)

**Comment by TarVK** [comment]
Hey @zularizal 
In general we really like the designs, especially the blue one with a slight gradient.
However, the logo doesn't fit the project a 100%. As it is supposed to be cross platform, with support for at least windows and mac, and possibly linux.
We are creating something that is similar to something that can be found on mac, so it isn't entirely off, but we are afraid it will scare away windows users. As they might think it is a mac only thing once they see the logo.

We are still considering if we can use this logo or not, but do you think there might be a good alternative that doesn't imply it is just for mac?

**Comment by zularizal** [comment]
Okay @TarVK , I will make an alternative logo for this logo.

**Comment by TarVK** [comment]
Lets continue this discussion in the relevant repository:
https://github.com/LaunchMenu/LaunchMenu/issues/1
