### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [TarVK/Yoke#2]
Hi,

Since this app is MIT licensed, are you considering the fact to add the android part to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by TarVK** [comment]
Hi there!

I had never heard of F-Droid, it seems interesting. I however don't really want to do anything with Yoke at this point in time, since I am trying to focus on new projects :)

Anyone else is more than welcome to add it to F-Droid though, and generally do whatever he/she wants with it!

**Comment by Poussinou** [comment]
Here you go with the RFP: https://gitlab.com/fdroid/rfp/issues/1224
